<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>


	<ItemGroup>
		<PackageReference Include="UnityEngine.Modules" Version="2022.3.18" IncludeAssets="compile" />
	</ItemGroup>

	<Target Name="PackageMod" AfterTargets="Publish">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="../thunderstore/build/dll" SkipUnchangedFiles="true" />
	</Target>
</Project>
